import { op, jsonBody, stringPathParam } from '../helpers.js';

export function corePaths() {
  return {
    '/health': {
      get: op({
        summary: 'Health check',
        tag: 'System',
        auth: false,
        responses: {
          200: {
            description: 'Service health status',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/HealthResponse' } } },
          },
        },
      }),
    },
    '/api/v1/version': {
      get: op({
        summary: 'Get application version',
        tag: 'System',
        auth: false,
        description: 'Public bootstrap metadata for login/setup. When a valid session or API token is supplied, the response also includes the exact app version.',
        responses: {
          200: {
            description: 'Application version',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/VersionResponse' } } },
          },
        },
      }),
    },
    '/api/v1/openapi.json': {
      get: op({
        summary: 'Get OpenAPI specification',
        tag: 'System',
        admin: true,
        description: 'Use `?download=1` to receive the OpenAPI document as a downloadable file.',
      }),
    },
    '/api/v1/changelog': {
      get: op({
        summary: 'Get release changelog',
        tag: 'System',
        description: 'Returns the current installed version, latest upstream release version, and sanitized release notes from the Yuvomi GitHub releases feed.',
      }),
    },
    '/openapi.json': {
      get: op({
        summary: 'Get OpenAPI specification',
        tag: 'System',
        admin: true,
        description: 'Alias for `/api/v1/openapi.json`. Use `?download=1` to download the JSON file.',
      }),
    },
    '/docs': {
      get: op({
        summary: 'API documentation',
        tag: 'System',
        admin: true,
        responses: { 200: { description: 'API documentation response' } },
      }),
    },
    '/feed/calendar/{token}.ics': {
      get: op({
        summary: 'Download personal calendar ICS feed',
        tag: 'Calendar',
        auth: false,
        description: 'Token-protected read-only ICS feed generated by `/api/v1/calendar/feed/regenerate`. The URL token is the secret.',
        params: [stringPathParam('token', 'Calendar feed token')],
        responses: {
          200: {
            description: 'ICS calendar feed',
            content: {
              'text/calendar': {
                schema: { type: 'string' },
              },
            },
          },
          404: { description: 'Feed token not found' },
          500: { $ref: '#/components/responses/InternalServerError' },
        },
      }),
    },
    '/feed/inventory-deadlines/{token}.ics': {
      get: op({
        summary: 'Download inventory deadlines ICS feed',
        tag: 'Inventory',
        auth: false,
        description: 'Token-protected read-only ICS feed of warranty end dates and tracked item dates, generated by `/api/v1/inventory/deadlines-feed/regenerate`. The URL token is the secret and belongs to one user, so it can be revoked individually; the feed content itself is household-wide.',
        params: [stringPathParam('token', 'Inventory deadlines feed token')],
        responses: {
          200: {
            description: 'ICS calendar feed',
            content: {
              'text/calendar': {
                schema: { type: 'string' },
              },
            },
          },
          404: { description: 'Feed token not found' },
          500: { $ref: '#/components/responses/InternalServerError' },
        },
      }),
    },
    '/feed/cycle/{token}.ics': {
      get: op({
        summary: 'Download predicted-cycle ICS feed',
        tag: 'Health',
        auth: false,
        description: 'Token-protected read-only ICS feed of logged and predicted periods (plus ovulation/fertile window when tracked), generated by `/api/v1/health/cycle/feed/regenerate`. Unlike the inventory deadlines feed, the feed CONTENT is personal, not just the token - it reflects only the token owner\'s own cycle data, with no household aggregation.',
        params: [stringPathParam('token', 'Cycle feed token')],
        responses: {
          200: {
            description: 'ICS calendar feed',
            content: {
              'text/calendar': {
                schema: { type: 'string' },
              },
            },
          },
          404: { description: 'Feed token not found' },
          500: { $ref: '#/components/responses/InternalServerError' },
        },
      }),
    },
    '/mcp': {
      get: op({
        summary: 'MCP endpoint method hint',
        tag: 'MCP',
        description: 'Returns 405 JSON-RPC guidance; use POST for MCP JSON-RPC requests.',
        responses: {
          405: { description: 'Method not allowed; use POST' },
          401: { $ref: '#/components/responses/Unauthorized' },
        },
      }),
      post: op({
        summary: 'Send MCP JSON-RPC request',
        tag: 'MCP',
        description: 'Stateless MCP Streamable HTTP endpoint. Intended for Bearer API-token authentication; session auth is also accepted by the shared auth middleware.',
        requestBody: jsonBody(null, 'JSON-RPC 2.0 request body'),
        responses: {
          200: { description: 'JSON-RPC response' },
          202: { description: 'JSON-RPC notification accepted' },
          400: { description: 'Invalid JSON-RPC request body' },
          401: { $ref: '#/components/responses/Unauthorized' },
          500: { $ref: '#/components/responses/InternalServerError' },
        },
      }),
    },
  };
}
