import { op, jsonBody } from '../helpers.js';

export function preferencesPaths() {
  return {
    '/api/v1/preferences': {
      get: op({ summary: 'Get user preferences', tag: 'Preferences', description: 'Household preferences. Language fields: `language` (explicitly chosen data language, or `null` for automatic), plus two read-only values — `language_effective` (what actually applies: `language`, else the language part of `region`, else `en`) and `language_auto` (what automatic mode alone would yield, ignoring `language`). The data language decides in which language the server *stores* content it generates itself, such as birthday event titles, so that the API, the ICS feed and calendar sync all agree. Weather fields: `weather_provider` (`open-meteo` | `openweathermap` | `null` = auto-detect from env), `weather_lat`, `weather_lon`, `weather_city`, `weather_units` (`metric` | `imperial`). Holiday fields: `holiday_country` (ISO-3166 alpha-2 or `null`), `holiday_subdivision` (e.g. `DE-BY` or `null`), `holiday_group` (school-holiday group for multilingual cantons, e.g. `CH-BE-VS`, or `null`), `holiday_show_public`, `holiday_show_school` (booleans), `holiday_public_color`, `holiday_school_color` (hex), `holiday_last_sync`.' }),
      put: op({ summary: 'Update user preferences', tag: 'Preferences', description: '`language` is admin-only: an ISO-639-1 code with a locale file, or `null`/`""` to fall back to automatic derivation from `region`. Changing it (or `region`, or `date_format`) re-titles the stored birthday events so every channel stays consistent. Weather fields (`weather_provider`, `weather_lat`, `weather_lon`, `weather_city`, `weather_units`) and holiday fields (`holiday_country`, `holiday_subdivision`, `holiday_group`, `holiday_show_public`, `holiday_show_school`, `holiday_public_color`, `holiday_school_color`) are admin-only. `weather_lat`/`weather_lon` are validated to ±90 / ±180; colors must be 6-digit hex. Module feature toggles `health_cycle_enabled` (show the health cycle tab) and `rewards_require_approval` (redemptions need admin approval) are admin-only booleans, both default `true`.', stateChanging: true, requestBody: jsonBody(null) }),
    },
    '/api/v1/preferences/holidays/countries': { get: op({ summary: 'List countries supported by OpenHolidays', tag: 'Preferences', description: 'Proxies the OpenHolidays API. Returns `{ data: [{ isoCode, name }] }` for the country dropdown.' }) },
    '/api/v1/preferences/holidays/subdivisions/{countryCode}': { get: op({ summary: 'List subdivisions for a country', tag: 'Preferences', params: [{ name: 'countryCode', in: 'path', required: true, schema: { type: 'string', pattern: '^[A-Z]{2}$' } }], description: 'Proxies the OpenHolidays API. Returns `{ data: [{ isoCode, name }] }` for the state/region dropdown.' }) },
    '/api/v1/preferences/holidays/groups/{countryCode}/{subdivisionCode}': { get: op({ summary: 'List school-holiday groups for a subdivision', tag: 'Preferences', params: [{ name: 'countryCode', in: 'path', required: true, schema: { type: 'string', pattern: '^[A-Z]{2}$' } }, { name: 'subdivisionCode', in: 'path', required: true, schema: { type: 'string', pattern: '^[A-Z]{2}-[A-Z0-9-]{1,10}$' } }], description: 'Proxies the OpenHolidays API. Returns `{ data: [{ code, name }] }` of school-holiday groups (multilingual cantons such as `CH-BE` split into e.g. `CH-BE-VS` / `CH-BE-EO`). Empty when the subdivision has a single school-holiday regime. Used to disambiguate overlapping same-named holidays (#434).' }) },
    '/api/v1/preferences/holidays/sync': { post: op({ summary: 'Sync holidays for the configured country', tag: 'Preferences', admin: true, stateChanging: true, description: 'Fetches public/school holidays from OpenHolidays for the configured country/subdivision and caches them. Returns `{ data: { last_sync } }`.' }) },
  };
}
